{
  "comments": [
    {
      "unresolved": true,
      "key": {
        "uuid": "12eca41c_aeeb5084",
        "filename": "ci-scripts/dlrnapi_promoter/config_environments/rdo/CentOS-9/zed.yaml",
        "patchSetId": 1
      },
      "lineNbr": 53,
      "author": {
        "id": 192
      },
      "writtenOn": "2022-09-27T08:04:33Z",
      "side": 1,
      "message": "locally:\n\u003e\u003e\u003e info \u003d {\u0027criteria\u0027:None}\n\u003e\u003e\u003e info[\u0027criteria\u0027] \u003d set(info[\u0027criteria\u0027])\nTraceback (most recent call last):\n  File \"\u003cstdin\u003e\", line 1, in \u003cmodule\u003e\nTypeError: \u0027NoneType\u0027 object is not iterable\n\n\u003e\u003e\u003e info \u003d {\u0027criteria\u0027:[]}\n\u003e\u003e\u003e info[\u0027criteria\u0027] \u003d set(info[\u0027criteria\u0027])\n\n\n\nerror coming from https://github.com/rdo-infra/ci-config/blob/70b88659b2663c7fc5bcf7e214efd39a71e2f58c/ci-scripts/dlrnapi_promoter/config.py#L441\n\nerror in promoter log http://promoter.rdoproject.org/promoter_logs/centos9_zed.log-20220925",
      "revId": "139c1a148301586c4f5cf4082b250b03983bce8b",
      "serverId": "270e2033-b340-4cff-9539-693957ebf0e7"
    }
  ]
}