{
  "comments": [
    {
      "key": {
        "uuid": "1571634f_3039eaf8",
        "filename": "/COMMIT_MSG",
        "patchSetId": 6
      },
      "lineNbr": 13,
      "author": {
        "id": 192
      },
      "writtenOn": "2020-06-17T07:14:58Z",
      "side": 1,
      "message": "https://tree.taiga.io/project/tripleo-ci-board/task/1744",
      "revId": "25f7a5dc01599dc1ad55dd562653157167bdad65",
      "serverId": "270e2033-b340-4cff-9539-693957ebf0e7",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "a3912342_58dba8d5",
        "filename": "ci-scripts/dlrnapi_promoter/promoter_defaults_experimental.yaml",
        "patchSetId": 6
      },
      "lineNbr": 15,
      "author": {
        "id": 192
      },
      "writtenOn": "2020-06-17T07:14:58Z",
      "side": 1,
      "message": "i guess this is to do with yaml \u0027null\u0027 vs ansible \u0027None\u0027\n\nso None was not working here? Was it set to the string \u0027None\u0027 for example? \n\nHow about if you just leave the value empty?",
      "revId": "25f7a5dc01599dc1ad55dd562653157167bdad65",
      "serverId": "270e2033-b340-4cff-9539-693957ebf0e7",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "7dcf0c66_b4d39943",
        "filename": "ci-scripts/dlrnapi_promoter/promoter_integration_checks.py",
        "patchSetId": 6
      },
      "lineNbr": 153,
      "author": {
        "id": 371
      },
      "writtenOn": "2020-06-16T12:24:00Z",
      "side": 1,
      "message": "use of chdir in an anti-pattern as it can affect other tools. Please use a context manager approach to assure that cwd is restored when function exits.",
      "range": {
        "startLine": 153,
        "startChar": 8,
        "endLine": 153,
        "endChar": 29
      },
      "revId": "25f7a5dc01599dc1ad55dd562653157167bdad65",
      "serverId": "270e2033-b340-4cff-9539-693957ebf0e7",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "5da5ac34_dd90d874",
        "filename": "ci-scripts/dlrnapi_promoter/qcow_client.py",
        "patchSetId": 6
      },
      "lineNbr": 53,
      "author": {
        "id": 192
      },
      "writtenOn": "2020-06-17T07:14:58Z",
      "side": 1,
      "message": "is it safe to assume that this IOError is only because the image didn\u0027t exist? I\u0027m referring to the log.error text on the next line",
      "range": {
        "startLine": 53,
        "startChar": 19,
        "endLine": 53,
        "endChar": 22
      },
      "revId": "25f7a5dc01599dc1ad55dd562653157167bdad65",
      "serverId": "270e2033-b340-4cff-9539-693957ebf0e7",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "1fb11c30_5eba607c",
        "filename": "ci-scripts/dlrnapi_promoter/qcow_client.py",
        "patchSetId": 6
      },
      "lineNbr": 168,
      "author": {
        "id": 371
      },
      "writtenOn": "2020-06-16T12:24:00Z",
      "side": 1,
      "message": "use \"qcow\", without capital, is a file format/extension. (or full caps if you want).",
      "range": {
        "startLine": 168,
        "startChar": 22,
        "endLine": 168,
        "endChar": 26
      },
      "revId": "25f7a5dc01599dc1ad55dd562653157167bdad65",
      "serverId": "270e2033-b340-4cff-9539-693957ebf0e7",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "03add73c_1c997dfb",
        "filename": "ci-scripts/dlrnapi_promoter/qcow_client.py",
        "patchSetId": 6
      },
      "lineNbr": 174,
      "author": {
        "id": 192
      },
      "writtenOn": "2020-06-17T07:14:58Z",
      "side": 1,
      "message": "as above... not sure if that will be confusing if the error is because of something else.\n\n\u0027unable to stat the directory _foo_\u0027 (giving full path for debug)",
      "range": {
        "startLine": 174,
        "startChar": 30,
        "endLine": 174,
        "endChar": 52
      },
      "revId": "25f7a5dc01599dc1ad55dd562653157167bdad65",
      "serverId": "270e2033-b340-4cff-9539-693957ebf0e7",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "a366589c_f8cca404",
        "filename": "ci-scripts/dlrnapi_promoter/qcow_client.py",
        "patchSetId": 6
      },
      "lineNbr": 185,
      "author": {
        "id": 192
      },
      "writtenOn": "2020-06-17T07:14:58Z",
      "side": 1,
      "message": "again... what if the error is actually during the removal operation, i don\u0027t know e.g. because of some permissions issue? The debug message may be confusing",
      "range": {
        "startLine": 185,
        "startChar": 32,
        "endLine": 185,
        "endChar": 52
      },
      "revId": "25f7a5dc01599dc1ad55dd562653157167bdad65",
      "serverId": "270e2033-b340-4cff-9539-693957ebf0e7",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "2ab624a9_b6542fab",
        "filename": "ci-scripts/dlrnapi_promoter/qcow_client.py",
        "patchSetId": 6
      },
      "lineNbr": 210,
      "author": {
        "id": 192
      },
      "writtenOn": "2020-06-17T07:14:58Z",
      "side": 1,
      "message": "am wondering how we can make this entire method more like an atomic operation. It isn\u0027t an easy/trivial thing (unless there are some python libraries that can help).\n\nIf any of these errors are encountered, can we restore the state to how it was previously?\ne.g. you remove the current hash successfully but then fail to create the link here for the new one (candidate_hash).",
      "revId": "25f7a5dc01599dc1ad55dd562653157167bdad65",
      "serverId": "270e2033-b340-4cff-9539-693957ebf0e7",
      "unresolved": false
    }
  ]
}