{
  "comments": [
    {
      "key": {
        "uuid": "69cc38fc_d830ce9b",
        "filename": "/COMMIT_MSG",
        "patchSetId": 83
      },
      "lineNbr": 27,
      "author": {
        "id": 192
      },
      "writtenOn": "2020-09-25T14:48:53Z",
      "side": 1,
      "message": "k confirmed the molecule tripleo-common integration is failing as a result of https://review.opendev.org/#/c/746477/ \u0026 its depends-on  \n\nwith the added debug from today:\n\n        * https://logserver.rdoproject.org/81/28081/83/check/mol-tripleo_common_integration/d3c8d5c/tox/reports.html\n        *     2020-09-25 13:02:48.018 48372 ERROR tripleoclient.v1.container_image.TripleoImagePrepare [-] Exception occured while running the command: RuntimeError: No such playbook: /usr/share/ansible/tripleo-playbooks/cli-container-image-prepare.yaml",
      "revId": "4e5d4b4e891d7a32739d5efaedb57091455dd40b",
      "serverId": "270e2033-b340-4cff-9539-693957ebf0e7",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "0c66a9ba_9cbf560d",
        "filename": "molecule/tripleo_common_integration/converge.yml",
        "patchSetId": 83
      },
      "lineNbr": 13,
      "author": {
        "id": 192
      },
      "writtenOn": "2020-09-25T12:56:25Z",
      "side": 1,
      "message": "as discussed just now in call we are trying to get more logs into https://logserver.rdoproject.org/81/28081/82/check/mol-tripleo_common_integration/10d9581/tox/reports.html",
      "range": {
        "startLine": 13,
        "startChar": 16,
        "endLine": 13,
        "endChar": 17
      },
      "revId": "4e5d4b4e891d7a32739d5efaedb57091455dd40b",
      "serverId": "270e2033-b340-4cff-9539-693957ebf0e7",
      "unresolved": false
    }
  ]
}