{
  "comments": [
    {
      "key": {
        "uuid": "e30eb4ce_ee22c2d9",
        "filename": "ci-scripts/infra-setup/roles/rrcockpit/files/telegraf/requirements.txt",
        "patchSetId": 39
      },
      "lineNbr": 4,
      "author": {
        "id": 192
      },
      "writtenOn": "2020-12-14T08:28:42Z",
      "side": 1,
      "message": "10:24 \u003c marios\u003e bhagyashris: akahat|ruck: seems like this is one of the main errors there AttributeError: \n                module \u0027graphene\u0027 has no attribute \u0027DateTime\u0027 \n10:25 \u003c marios\u003e bhagyashris: akahat|ruck: i don\u0027t know if that is coming from newer things in test-requirements \n                though, or if now you have fixed the requirements issue you are just hitting something new.\n10:27 \u003c marios\u003e bhagyashris: akahat|ruck: perhaps you need to get newer dlrnapi_client in \nhttps://review.rdoproject.org/r/#/c/28014/38..39/ci-scripts/infra-setup/roles/rrcockpit/files/telegraf/requirements.txt ?\n10:27 \u003c akahat|ruck\u003e marios, yes.. i think we are hitting new issue.\n10:27 \u003c marios\u003e bhagyashris: akahat|ruck: looks like it is throwing that from import there https://logserver.rdoproject.org/14/28014/39/check/tox-py36-ci-config/5d80b83/tox/reports.html from dlrn.api import app AttributeError: module \u0027graphene\u0027 has no attribute \u0027DateTime\u0027",
      "range": {
        "startLine": 4,
        "startChar": 0,
        "endLine": 4,
        "endChar": 14
      },
      "revId": "a16f6f6b9a11a02c73bb9e5ff278b1de0578c4f3",
      "serverId": "270e2033-b340-4cff-9539-693957ebf0e7",
      "unresolved": false
    }
  ]
}