{
  "comments": [
    {
      "unresolved": false,
      "key": {
        "uuid": "cc45c11b_83a0bf52",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 27
      },
      "lineNbr": 0,
      "author": {
        "id": 111
      },
      "writtenOn": "2022-06-21T04:24:32Z",
      "side": 1,
      "message": "Nice addition.",
      "revId": "ec4e913a1b31234755bea748169ab8e79ecc1e28",
      "serverId": "270e2033-b340-4cff-9539-693957ebf0e7"
    },
    {
      "unresolved": true,
      "key": {
        "uuid": "3431e822_bbb6862a",
        "filename": "playbooks/shellcheck_run.yml",
        "patchSetId": 27
      },
      "lineNbr": 21,
      "author": {
        "id": 111
      },
      "writtenOn": "2022-06-21T04:24:32Z",
      "side": 1,
      "message": "Can we change it to \u0027\u003d\u003d 0\u0027 so that we can catch the issue if any other exit status comes we can catch it and fail the job so that people can debug it?",
      "range": {
        "startLine": 21,
        "startChar": 40,
        "endLine": 21,
        "endChar": 41
      },
      "revId": "ec4e913a1b31234755bea748169ab8e79ecc1e28",
      "serverId": "270e2033-b340-4cff-9539-693957ebf0e7"
    }
  ]
}